import { Heart, MessageCircle, Send, Bookmark, MoreHorizontal } from "lucide-react";
import { MockShell } from "@/components/product-mocks/MockShell";

// Instagram-style post preview generated by the content agent.
export function ContentFeed({ className }: { className?: string }) {
  return (
    <MockShell
      kind="app"
      title="Content Studio"
      subtitle="Instagram · Scheduled"
      trailing={
        <span className="inline-flex items-center gap-1 rounded-pill bg-accent/40 px-2 py-0.5 text-[10px] font-semibold text-ink">
          3 platforms
        </span>
      }
      footer={
        <div className="flex items-center justify-between">
          <span>Auto-posts 9:00 AM</span>
          <span>On brand voice</span>
        </div>
      }
      className={className}
    >
      <div className="flex h-full flex-col">
        <div className="flex items-center gap-2.5 px-3 py-2.5">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src="https://picsum.photos/seed/dolo-handle/80/80"
            alt=""
            className="h-8 w-8 rounded-full object-cover"
          />
          <div className="leading-tight">
            <p className="text-[12.5px] font-semibold text-ink">northbeam.realty</p>
            <p className="text-[10.5px] text-ink/50">Linden Ave</p>
          </div>
          <MoreHorizontal className="ml-auto h-4 w-4 text-ink/50" />
        </div>

        <div className="relative min-h-0 flex-1">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src="https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=720&h=720&q=80"
            alt="Generated social post: a modern living room of the listed home"
            className="h-full w-full object-cover"
          />
        </div>

        <div className="flex items-center gap-4 px-3 py-2.5 text-ink">
          <Heart className="h-5 w-5 fill-accent text-accent" />
          <MessageCircle className="h-5 w-5" />
          <Send className="h-5 w-5" />
          <Bookmark className="ml-auto h-5 w-5" />
        </div>

        <div className="px-3 pb-3 text-[12px] leading-snug">
          <p className="font-semibold text-ink">1,248 likes</p>
          <p className="mt-0.5 text-ink/80">
            <span className="font-semibold text-ink">northbeam.realty</span> Just listed in
            the heart of the district. Book a private tour this weekend.
          </p>
        </div>
      </div>
    </MockShell>
  );
}
